slife:
  rate: 1
  synth_pcl_size: 10
  topics:
    pointcloud: /camera/depth/pointcloud
    debug_grid: /slife/debug_grid
  landscape:
    measure_radius: 0.7
    smooth_radius: 0.01
    precision: 10
  optimizer:
    step_sizes: [0.3, 0.1]
    threshold: 0.01
    cost:
      batch_size: 10
  debug:
    test_grid:
      min: -1.0
      max: 1.0
      step: 0.06
    z_test_value: 0.
    test_type: cost_value # options: {none, landscape_value, landscape_gradient, cost_value, cost_gradient}