slife:
  rate: 1
  synth_pcl_size: 1000
  topics:
    pointcloud: /camera/depth/pointcloud
    debug_grid: /slife/debug_grid
  landscape:
    measure_radius: 0.7
    smooth_radius: 0.01
    precision: 100
  optimizer:
    ciao: come
  debug:
    test_grid:
      min: -1.0
      max: 1.0
      step: 0.06
    z_test_value: 0.
    test_type: gradient # options: {value, gradient}